In [3]:
import numpy as np

In [51]:
y = np.full((2, 3), 2)
yhat = np.full((2, 3), -2)
print(y, yhat)

[[2 2 2]
 [2 2 2]] [[-2 -2 -2]
 [-2 -2 -2]]


In [52]:
np.square(np.linalg.norm(y - yhat, axis=-1))

array([48., 48.])

In [1]:
from loss import MSELoss
from module import Linear
import torch

In [13]:
x = np.random.randn(100, 3)
y = np.hstack((np.expand_dims(x[:, 0] + 2 * x[:, 1], 1), np.expand_dims(x[:, 0] + x[:, 1] + 5 * x[:, 2], 1)))

module = Linear(3, 2)
loss = MSELoss()

for _ in range(100):
    yhat = module.forward(x)
    delta1 = loss.backward(y, yhat)

    module.backward_update_gradient(x, delta1)
    module.update_parameters()
    module.zero_grad()

In [14]:
module.forward(np.array([[1, 2, 3]]))

array([[ 4.99999999, 17.99999998]])

In [55]:
x = torch.randn(100, 2)
y = x[:, 0] + 2 * x[:, 1]
y = torch.unsqueeze(y, 1)

m = torch.nn.Linear(2, 1)
l = torch.nn.MSELoss()
optim = torch.optim.SGD(m.parameters(), lr=0.001)

for _ in range(10000):
    optim.zero_grad()

    outputs = m(x)
    loss = l(outputs, y)
    loss.backward()
    optim.step()

In [60]:
m(torch.Tensor([1, 3]))

tensor([6.9999], grad_fn=<AddBackward0>)